name: productivity_hub
description: "Productivity Hub - комплексное решение для повышения продуктивности"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  rxdart: ^0.28.0

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # Google APIs
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Date & Time
  intl: ^0.19.0
  timezone: ^0.9.4

  # Notifications
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

  # AI & ML
  http: ^1.2.2
  langchain: ^0.7.5
  langchain_openai: ^0.7.3

  # Utils
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
